[Simulator] Hide the Balance button
bancorprotocol/carbon-app pull request #1075
Opened 2024-02-23 11:10 UTC by GrandSchtroumpf

fix #1074 

- [x] Create a button to hide balance
- [x] Hide flickering when chart is transitioning 

https://github.com/bancorprotocol/carbon-app/assets/8143464/1917e270-2a6d-42db-8c1b-abaf3f8d0a0d

- [x] Add focus & keyboard navigation for summary

https://github.com/bancorprotocol/carbon-app/assets/8143464/8feff9bf-88b0-4548-a3b3-7a8c540ad41f

2024-02-23 11:57 UTC, tiagofilipenunes approved these changes

2024-02-23 11:57 UTC, tiagofilipenunes commented on src/components/simulator/result/d3Charts/D3ChartSimulatorBalance.tsx
> +  const x = isVisible ? center + titleWidth / 2 + marginLeft : center / 2 + 6;
```suggestion
  const x = isVisible ? center + titleWidth / 2 + marginLeft : center -16;
```

2024-02-23 11:57 UTC, tiagofilipenunes commented
Good job, looks great!

2024-02-23 16:19 UTC, pingustar requested changes
- [ ] there are super large borders around the buttons now

<img width="426" alt="image" src="https://github.com/bancorprotocol/carbon-app/assets/7262066/47461920-41a4-4127-a7a0-98d0e8e6f13b">
<img width="456" alt="image" src="https://github.com/bancorprotocol/carbon-app/assets/7262066/5b903a8a-3cdc-47e3-ad39-8eb0fe60c72d">

2024-02-23 16:25 UTC, pingustar submitted a review, later dismissed
- [x] there are super large borders around the buttons now

<img width="426" alt="image" src="https://github.com/bancorprotocol/carbon-app/assets/7262066/47461920-41a4-4127-a7a0-98d0e8e6f13b">
<img width="456" alt="image" src="https://github.com/bancorprotocol/carbon-app/assets/7262066/5b903a8a-3cdc-47e3-ad39-8eb0fe60c72d">

---

- [x] eye icons are to close to the edge now

now:
<img width="215" alt="image" src="https://github.com/bancorprotocol/carbon-app/assets/7262066/51b946bd-b75a-4332-b5dc-1ce0097d4c70">

before:
<img width="217" alt="image" src="https://github.com/bancorprotocol/carbon-app/assets/7262066/30fc63ae-429f-4c70-a52e-d5aa57ed9d0d">

2024-02-26 12:00 UTC, ashachaf approved these changes

2024-02-26 13:52 UTC, merged