Update fonts
bancorprotocol/carbon-app pull request #1140
Opened 2024-03-27 14:36 UTC by GrandSchtroumpf

2024-04-02 10:41 UTC, Leeseli commented
Hi, here are the texts that need to be updated:

- [ ] create strategy page- "next step" button needs to be BW 
<img width="623" alt="image" src="https://github.com/bancorprotocol/carbon-app/assets/159428318/413148bd-b988-4e34-b012-6a0acb4535d4">

- [ ] my strategy page- "create your first.." needs to be BW 
<img width="665" alt="image" src="https://github.com/bancorprotocol/carbon-app/assets/159428318/07c7fc27-1b1d-488a-b5dd-66506bc76fce">

- [ ] trade page - "buy" and "sell" buttons, text font should be 16px and bold.
<img width="1140" alt="image" src="https://github.com/bancorprotocol/carbon-app/assets/159428318/250085b6-31f2-493f-8fb9-fae251b88adf">

thank you!

2024-04-18 14:50 UTC, tiagofilipenunes commented on src/components/simulator/result/SimResultSummary.tsx
> +              `}
buttonStyles doesn't apply white-space, so it's fine not to use cn()

2024-04-18 14:52 UTC, tiagofilipenunes commented on src/components/strategies/create/CreateStrategyTypeMenu.tsx
> +        `}
buttonStyles applies the same opacity and cursor-not-allowed, so I think it's fine not to use cn(), please confirm that's intended

2024-04-18 15:03 UTC, tiagofilipenunes commented on src/components/core/menu/mainMenu/MainMenuRightWallet.tsx
> +            <span>{buttonText}</span>
Assuming removing font-mono here won't affect e2e screenshots

2024-04-18 15:05 UTC, tiagofilipenunes commented on e2e/screenshots/strategy/recurring/Recurring limit range/editPrices/form.jpg
Strategy budget distribution text is wrapping here

2024-04-18 15:10 UTC, tiagofilipenunes requested changes
Looks beautiful! 🎉

Observed:
- Ethereum Network text in the user wallet dropdown now wrapping
Before:

<img width="228" alt="Screenshot 2024-04-18 at 15 33 00" src="https://github.com/bancorprotocol/carbon-app/assets/66181828/16b6c37a-0974-4b31-939e-b631ab552306">

After:
<img width="230" alt="Screenshot 2024-04-18 at 15 32 54" src="https://github.com/bancorprotocol/carbon-app/assets/66181828/4ad13d94-600d-4063-abbc-a1baa9e9fd8a">

- Titles all appropriately assigned, WarningMessageWithIcon applied everywhere 🤌
- Clearer to read numbers in charts (simulator, strategy block and overlapping graph)

Places where the new fonts weren't applied:
- [x] Browser default font being used in the trade page on the tooltip when hovering the depth chart
- [ ] Browser default font being used in the tooltip when hovering the portfolio pie chart

2024-04-22 07:11 UTC, GrandSchtroumpf commented on e2e/screenshots/strategy/recurring/Recurring limit range/editPrices/form.jpg
Lee decided to keep it in two lines

2024-04-22 10:00 UTC, tiagofilipenunes approved these changes

2024-05-02 06:46 UTC, ashachaf approved these changes

2024-05-02 07:53 UTC, merged