Replace "overlapping" with "concentrated liquidity"
bancorprotocol/carbon-app pull request #1256
Opened 2024-06-10 10:16 UTC by GrandSchtroumpf

fix #1241

2024-06-11 09:42 UTC, ashachaf commented
- [ ] simulate page
replace "overlapping" with "concentrated liquidity" (if doesnt fit, try using "concentrated" only)
<img width="472" alt="image" src="https://github.com/bancorprotocol/carbon-app/assets/40430285/f7a39639-c627-42f0-99aa-cb1cd1c118f0">

- [ ] simulate result page
<img width="265" alt="image" src="https://github.com/bancorprotocol/carbon-app/assets/40430285/98b5e3b3-488b-46e3-8d0d-76f9b693060f">
replace "overlapping" with "concentrated liquidity"

2024-06-11 17:21 UTC, tiagofilipenunes commented on src/components/strategies/create/useCreateStrategyTypeMenu.tsx
>        'A concentrated position where you buy and sell in a custom price range, used to create a bid-ask spread that moves as the market does',
```suggestion
      'A concentrated position where you buy and sell in a custom price range, used to create a bid-ask fee tier that moves as the market does',
```

2024-06-11 17:37 UTC, tiagofilipenunes requested changes
- [x] When selecting "Duplicate strategy", the modal text for undercutting a strategy says:

"Set prices at 0.1% tighter spread and try to get filled ahead"

![image](https://github.com/bancorprotocol/carbon-app/assets/66181828/0a5b6baa-cf85-4452-9148-81564a48529c)

- [x] Readme mentions spread, consider adding feeTier in parenthesis so it's not confusing. 

Apart from this, the code mentions spread throughout and it is not obvious that 'feeTier' == 'spread', at some point this replacement should happen at the code level.

- [x] Readme mentions

```
- `ETH/BNT`: Create overlapping strategy
```

Replace by 

```
- `ETH/BNT`: Create concentrated liquidity strategy
```

Also, overlapping is mentioned throughout the app, even in tests which adds confusion as it's not obvious that 'concentrated liquidity' == 'overlapping'


Feel free to create a new issue for these:
- [x] In src/components/simulator/input/SimInputStrategyType.tsx, the label being different from the title in items will impair accessibility. This may happen elsewhere, so it may be worth investigating accessibility inconsistencies.

- [x] Deeplinks mentioning overlapping, should probably be changed to concentrated, with redirects created if we're going to commit to this change.

- [ ] The FAQ in this link should be updated: https://faq.carbondefi.xyz/strategy-types/overlapping-liquidity @ashachaf

2024-06-12 15:03 UTC, tiagofilipenunes approved these changes

2024-06-12 15:03 UTC, merged