[Overlapping] Enable undercut
bancorprotocol/carbon-app pull request #1357
Opened 2024-07-16 07:58 UTC by GrandSchtroumpf

fix #1325

Enable undercut for overlapping strategy
Reduce spread by 0.1%.

Test cases : 
1. Create an overlapping strategy with spread of 1%
2. Menu -> Duplicate -> Undercut 
3. Spread is now 0.99%

This work if strategy :
- has no budget nor market price
- is above/below market price
- are built out of a recurring strategy (default to 0.05*0.99)

2024-07-16 09:15 UTC, tiagofilipenunes approved these changes
LGTM

Only thing to note is if the overlapping strategy has a defined budget, this budget (and anchor) won't be populated when undercutting, which is the same behaviour as overlapping duplicate but different from recurring/disposable undercut/duplicate.

2024-07-16 09:55 UTC, ashachaf commented
- [ ] remove duplicate option from strategies with no prices
IF order0.buyLow AND order0.sellHigh AND order1.buyLow AND order1.sellHigh = 0, remove the duplicate option from the menu

- [ ] duplicating recurring strategy opens concentrated creation
https://github.com/user-attachments/assets/23310a69-ceaa-4f04-93a7-ee9b8e1db32e
https://github.com/user-attachments/assets/2b4734b4-4d54-4d78-b973-0ed2c841e2fd

2024-07-17 14:19 UTC, tiagofilipenunes requested changes
LGTM just one change request for the e2e test

1. Currently, the create/duplicate/undercut tests all override the create/form.png screenshot. Can you change the submit method of CreateStrategyDriver to something like this

```typescript
  async submit(type: StrategyCase) {
    const btn = this.page.getByText('Create Strategy');
    if (shouldTakeScreenshot) {
      const mainMenu = new MainMenuDriver(this.page);
      await mainMenu.hide();
      await waitTooltipsClose(this.page);
      const form = this.getForm();
      const path = screenshotPath(this.testCase, type, 'form');
      await screenshot(form, path);
      await mainMenu.show();
    }
    try {
      await waitFor(this.page, 'approve-warnings', 2_000);
      if (await this.page.isVisible('[data-testid=approve-warnings]')) {
        await this.page.getByTestId('approve-warnings').click();
      }
      await btn.click();
    } catch {
      await btn.click({ timeout: 1_000 });
    }
  }
```

and then set they type to the strategy type.

2024-07-17 14:19 UTC, tiagofilipenunes commented on src/libs/modals/modals/ModalDuplicateStrategy/ModalDuplicateStrategy.tsx
> +  if (isBuyEmpty || isSellEmpty) return 'disposable';
Could you use `isDisposableStrategy` from `src/components/strategies/common/utils.ts` here?

2024-07-17 15:51 UTC, tiagofilipenunes approved these changes

2024-07-18 08:11 UTC, merged