[Overlapping] Display Spread on Strategy Card
bancorprotocol/carbon-app pull request #1362
Opened 2024-07-16 14:36 UTC by GrandSchtroumpf

fix #1096 

Add spread on overlapping strategy card tooltip
![image](https://github.com/user-attachments/assets/ecda845b-0fec-4f1f-8f7a-c70bd017d1a1)

2024-07-16 14:41 UTC, ashachaf approved these changes

2024-07-16 15:10 UTC, tiagofilipenunes requested changes
LGTM. 

Works on my strategies, strategy page, explore, with empty strategy, with offline api. E2E tests look good and spread testing is covered.

2024-07-16 15:29 UTC, GrandSchtroumpf commented on e2e/screenshots/strategy/recurring/Recurring limit range/create/form.png
hmmm the main question is why it was 1698 in the first place. The E2E specify it to be 1700...
The buy price should be 1500. I'm surprise the output is good though...
I think it's a bug unrelated to the PR

2024-07-17 08:13 UTC, GrandSchtroumpf commented on e2e/screenshots/strategy/recurring/Recurring limit range/create/form.png
I created an issue to tackle this is another PR : 
https://github.com/bancorprotocol/carbon-app/issues/1364

2024-07-17 08:23 UTC, tiagofilipenunes commented on e2e/screenshots/strategy/recurring/Recurring limit range/create/form.png
Works for me 👍

2024-07-17 08:23 UTC, tiagofilipenunes approved these changes

2024-07-17 09:20 UTC, merged