[Activity] Fix countdown
bancorprotocol/carbon-app pull request #1371
Opened 2024-07-24 10:32 UTC by GrandSchtroumpf

Commit style & cancel animation before running a new one.

2024-07-24 11:08 UTC, ashachaf approved these changes

2024-07-24 14:37 UTC, tiagofilipenunes requested changes
Code LGTM, notes/issues with the counter:

- My counter got stuck on "1" after 5 attempts of refresh. After 30 seconds it restarted
- Counter moves when tab is active and on other windows, and refreshes on focus. I think this is good

2024-07-24 14:37 UTC, tiagofilipenunes commented on src/components/activity/ActivityCountDown.tsx
> +    duration: Math.max(duration - delta, 0),
fix #1289

2024-07-24 14:37 UTC, tiagofilipenunes commented on src/components/activity/ActivityCountDown.tsx
> +  animations.forEach(async (a) => {
```suggestion
  animations.forEach((a) => {
```

2024-07-25 13:34 UTC, tiagofilipenunes approved these changes

2024-07-25 13:37 UTC, merged