Trade Page - bis
bancorprotocol/carbon-app pull request #1431
Opened 2024-08-19 13:08 UTC by GrandSchtroumpf

2024-08-20 12:16 UTC, Costa769 commented
-[ ] Swap between tokens resets to default strategy type
When user clicks on the arrow icon and swaps between base and quote tokens, the strategy selection resets to default
![image](https://github.com/user-attachments/assets/2bf1738a-8b91-4361-ad1c-094f415a8d97)

2024-08-20 18:37 UTC, Costa769 commented
- [ ] Remove the border from gear icon
On Spot trade page, remove the border around the gear icon, see example below
![image](https://github.com/user-attachments/assets/211652d9-0050-401f-872f-ff54693a4961)

- [ ] Change checkbox text
Update checkbox text on concentrated strategy page
Current: "I've reviewed the warning(s) but choose to proceed."
New: "I've approve the token deposit(s) and distribution"

- [ ] Update "Notice" text on the spot strategy page
Current:
![image](https://github.com/user-attachments/assets/6adf9c96-9584-4423-81db-361724580715)
Updated:
![image](https://github.com/user-attachments/assets/36474a28-14de-4958-aced-b2115fb73f02)

2024-08-21 09:39 UTC, Costa769 commented
### Optional

- [ ] Add strategy type to the create strategy CTA
For all strategy types except spot, add strategy type indication to the create strategy CTA
**Strategy type -> Text to show on the CTA**
Recurring strategy type -> show "Create Recurring Strategy" 
Concentrated strategy type-> show "Create Concentrated Strategy" 
Limit/Range strategy type
- **IF** user selected limit-> show "Create Limit Strategy" 
- **ELSE,IF** user selected range-> show "Create Range Strategy"

Example(recurring):
![image](https://github.com/user-attachments/assets/73f8140f-01df-4617-9114-ea9a48b174c5)

2024-08-21 12:10 UTC, Costa769 commented
- [ ] Change Spot Sell/Buy form titles
Current: 
![image](https://github.com/user-attachments/assets/90aa6031-e69b-4da0-930c-32e55707fbfc)
Update:
Sell tab-> Change "Sell High ETH" to "Sell ETH for USDC"
Buy tab-> Change "Buy Low ETH" to "Buy ETH with USDC"

- [ ] Add rebase and fee tokens warning in the token selection section
![image](https://github.com/user-attachments/assets/f926733a-d6d9-4907-ac73-592f16c6261b)

- [ ] Add token pair tooltip
Add the same token pair tooltip that we currently show on the first step of the strategycreation flow
![image](https://github.com/user-attachments/assets/31bcc31e-46c5-4bb6-a393-7ad550120524)

- [ ] Add "Buy or Sell" and "With" indicators to the token selection fields
![image](https://github.com/user-attachments/assets/0b40047d-1f99-4874-a509-9ee26ed5fd50)

- [ ] Add Buy low and Sell high tooltips for limit/range and recurring strategies
Those are the same tooltips currently implemented, example:
![image](https://github.com/user-attachments/assets/7500dbf8-55f0-41a5-a947-e76550c88fbc)

- [ ] Add "i" icons woth tooltips for strategy types
The tooltip will be shown when mouse hover over the "i" icon inside the strategy option, similar behavior to the one on the simulate page
![image](https://github.com/user-attachments/assets/348fba21-9cfc-4370-800d-4fa572636881)

2024-08-21 16:44 UTC, tiagofilipenunes requested changes
Great work on the update of the trade page!

Notes:
- Can you make the Strategy Type tooltip icons 12x12px size and the hover outline-background-400 in the Strategy Type options and the select token buttons to match the simulator form?
- Shouldn't e2e screenshots change here?
- In the Trading Strategy component, for narrow screens, the concentrated icon disappears. Example at 416px.
<img width="414" alt="image" src="https://github.com/user-attachments/assets/df07a0bd-1ce1-46f2-82a4-be92fea0a8ec">

- Old url subpath like 
```
/strategies/create/recurring?base=0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE&quote=0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48
```
Are not redirected right now to 

```
/trade/recurring?base=0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE&quote=0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48
```

2024-08-21 16:44 UTC, tiagofilipenunes commented on src/libs/routing/routes/trade.ts
> +  buySettings: StrategySettings;
Can be optional as the default is `limit`

2024-08-21 16:44 UTC, tiagofilipenunes commented on src/libs/routing/routes/trade.ts
> +  sellBudget?: string;
Can be optional as the default is `limit`

2024-08-22 05:27 UTC, Costa769 commented
- [ ] Update "No liquidity available" warning text
When Spot option is selected and there is no liquidity available for the selected pair, we show the following message:
![image](https://github.com/user-attachments/assets/8b2a5798-548e-40de-8030-5a4dccc79f04)

Update the text to:

"Looks like there isn't sufficient liquidity to execute your trade, but don’t worry, here's a pro tip: 
Set your own price with a limit/range order and the built-in solver system will search chain-wide liquidity to help efficiently fill you order, all while you enjoy MEV sandwich attack resistance, zero slippage, and zero fees!"

- [ ] Mobile view is broken
Maybe we can remove the token and strategy icons on mobile
![image](https://github.com/user-attachments/assets/ce3ccadc-571e-4516-90b9-a013d461a536)

2024-08-22 08:32 UTC, GrandSchtroumpf commented on src/components/activity/ActivitySection.tsx
> +  }
Not really because it uses `activityQuery` not `activityMetaQuery`.

2024-08-22 10:44 UTC, tiagofilipenunes approved these changes
LGTM, just minor comments

1. In the trade page, on the spot tab, I'm seeing these search params:

`&source=&target=`

2024-08-22 10:44 UTC, tiagofilipenunes commented on src/components/strategies/common/NoStrategies.tsx
> +export const NoStrategies = () => {
This component is not used anymore

2024-08-22 10:44 UTC, tiagofilipenunes commented on e2e/pages/trade.spec.ts
> +      // },
I'm okay with reducing the number of trades here. Can you remove the comment?

2024-08-22 11:10 UTC, merged