Concentrated Liquidity range chart
bancorprotocol/carbon-app pull request #1447
Opened 2024-08-26 16:18 UTC by GrandSchtroumpf

fix #1442

Add responsive graph into trade

What to test : 
1. go to trade, create concentrated liquidity
2. resize the screen from mobile to desktop
3. zoom in & out of the graph
4. move cursor around
5. change market price -> title changes
6. use PARQ token (not market price)

2024-08-27 13:51 UTC, Costa769 approved these changes

2024-08-27 14:11 UTC, tiagofilipenunes requested changes
LGTM 👍 Some suggestions:

- [x] Could the text in the Chart wrap for smaller screens?
<img width="369" alt="image" src="https://github.com/user-attachments/assets/f4b7a269-c14a-47b0-8c31-84cb2daa2a7c">

- [x] Can you add more vertical space for the history tab chart?
Before: 
<img width="413" alt="image" src="https://github.com/user-attachments/assets/d8460d5b-8bdd-4ce7-ac63-b007cd527563">

After:
<img width="401" alt="image" src="https://github.com/user-attachments/assets/2cc5fd89-376d-4ddb-8f5e-b3333421a89c">

- [ ] Can you add tabIndex to the Range/History labels for keyboard navigation highlighting?

2024-08-27 14:14 UTC, tiagofilipenunes commented on e2e/screenshots/strategy/overlapping/Overlapping/withdraw/form.png
Just flagging: don't see any difference in this screenshot

2024-08-27 15:30 UTC, tiagofilipenunes approved these changes

2024-08-28 07:07 UTC, ashachaf approved these changes

2024-08-28 07:32 UTC, merged